{% set name = "django-mfa2" %}
{% set name2 = "django_mfa2" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name2[0] }}/{{ name }}/{{ name2 }}-{{ version }}.tar.gz
  sha256: 38325751d88d64e88bbb76cd460e22dbde0880230f1839399ccef323a6c5bd4a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - django
    - jsonfield
    - pyotp
    - python-u2flib-server
    - ua-parser
    - user-agents
    - python-jose
    - fido2 ==1.1.3

test:
  requires:
    - python {{ python_min }}
  imports:
    - mfa

about:
  home: https://pypi.org/project/django-mfa2/
  summary: django-mfa2, A Django app that handles MFA, it supports TOTP, U2F, FIDO2 U2F (Web Authn), Email Tokens , and Trusted Devices
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
    - mkalioby
