{% set name = "django-mfa2" %}
{% set version = "3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3d4a56e696151cf72d0120deeb1f03290763e718315b572b6dffc505f0b1fa1d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - django
    - jsonfield
    - pyotp
    - python-u2flib-server
    - ua-parser
    - user-agents
    - python-jose
    - fido2 ==1.1.3

test:
  imports:
    - mfa

about:
  home: https://pypi.org/project/django-mfa2/
  summary: django-mfa2, A Django app that handles MFA, it supports TOTP, U2F, FIDO2 U2F (Web Authn), Email Tokens , and Trusted Devices
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
    - mkalioby
